services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev

    # Maps to 8000 as defined by APP_PORT,
    # if APP_PORT is not set, it defaults to 8000
    ports:
      - "${APP_PORT:-8000}:8000"

    env_file:
      - ./.env

    depends_on:
      - postgres

  postgres:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_PORT: ${PG_PORT}

    # This volume stores PostgreSQL data outside of the container filesystem,
    # preserving data between container restarts or recreations
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
