"""added_title_to_subtask

Revision ID: 2b12774af4a4
Revises: 0732306b01aa
Create Date: 2025-12-17 14:07:27.409465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b12774af4a4'
down_revision: Union[str, Sequence[str], None] = '0732306b01aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtasks', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subtasks', 'title')
    # ### end Alembic commands ###
