"""subtask_del_cascade

Revision ID: da2ad3bc7247
Revises: eecd4fb2c634
Create Date: 2026-04-21 18:40:26.098872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da2ad3bc7247'
down_revision: Union[str, Sequence[str], None] = 'eecd4fb2c634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subtasks', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('subtasks_todo_id_fkey'), 'subtasks', type_='foreignkey')
    op.create_foreign_key(None, 'subtasks', 'todos', ['todo_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subtasks', type_='foreignkey')
    op.create_foreign_key(op.f('subtasks_todo_id_fkey'), 'subtasks', 'todos', ['todo_id'], ['id'])
    op.alter_column('subtasks', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
